when:
  - event: push
    branch: [master, release, release/*]

depends_on:
  - build-amd64
  - build-arm64

matrix:
  platform:
    - linux/amd64

labels:
  platform: ${platform}

steps:
  - name: push
    image: quay.io/containers/podman
    environment:
      DOCKER_USER:
        from_secret: docker_user
      DOCKER_PASS:
        from_secret: docker_pass
    commands:
      - podman login reg.zerodoc.dev --username $DOCKER_USER --password $DOCKER_PASS
      - podman manifest create zerodoc/nomad_follower:${CI_COMMIT_BRANCH}
        --amend reg.zerodoc.dev/zerodoc/nomad_follower:${CI_COMMIT_BRANCH}-amd64 
        --amend reg.zerodoc.dev/zerodoc/nomad_follower:${CI_COMMIT_BRANCH}-arm64
      - podman manifest push zerodoc/nomad_follower:${CI_COMMIT_BRANCH}
        reg.zerodoc.dev/zerodoc/nomad_follower:${CI_COMMIT_BRANCH}
      - podman manifest inspect zerodoc/nomad_follower:${CI_COMMIT_BRANCH}
